### ISSUE TITLE
5x5 raster

### ISSUE THREAD

**Issue by vahidsamimi** [mck182/QNeuralNet#3]
Hi, 

i would like to run just a first example (recognizeNumber ) in your code but i have some problems!
how can I change your code so that this part itself learning without learnt weights.
Also when is variable train in line 616(mainwindow.cpp) true ?

tnx,
Vahid

**Comment by mck182** [comment]
> Also when is variable train in line 616(mainwindow.cpp) true

Whenever you set it to.

**Comment by vahidsamimi** [comment]
Thanks a lot.
Ok!!! 
but when i change the value to true, the network cant self learn!

**Comment by mck182** [comment]
Unless you give it impossible data, then it has no reason not to.

**Comment by vahidsamimi** [comment]
![screenshot from 2016-02-02 13-09-29](https://cloud.githubusercontent.com/assets/16437340/12749036/617d1d7c-c9ae-11e5-9c29-69965a6f1e44.png)

i changed just train = true
but output is false!

**Comment by mck182** [comment]
Works fine here. Clearly you must have done some other changes that make your neuron have "nan" as values.

![](http://paste.opensuse.org/view/raw/512b2e56)

**Comment by vahidsamimi** [comment]
you can upload your source code again, please?
Because i used your code without any change!

**Comment by mck182** [comment]
Code from this repo plus this:

``` diff
$ git diff
diff --git a/mainwindow.cpp b/mainwindow.cpp
index de8f4b2..c12757d 100644
--- a/mainwindow.cpp
+++ b/mainwindow.cpp
@@ -613,7 +613,7 @@ void MainWindow::recognizeNumber()
         m_netForRecognition = true;
     }

-    bool train = false;
+    bool train = true;
     if (train) {
         QList<QList<float> > trainSet;
         //prepare the train set

```
